In [2]:
#Import numpy as np and print the version number.
import numpy as np
np.version.version

'1.26.3'

In [ ]:
#Create a 1D array of numbers from 0 to 9
np.arange(0,9)
#Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Create a 3×3 numpy array of all True’s
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
#How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr
#input arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#output array([1, 3, 5, 7, 9])
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
#How to replace items that satisfy a condition with another value in numpy array?
#Replace all odd numbers in arr with -1

# Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Desired Output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#How to replace items that satisfy a condition without affecting the original array?
#Replace all odd numbers in arr with -1 without changing arr
# Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output: out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 = arr.copy()
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1[1::2]=-1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#How to reshape an array?
#Convert a 1D array to a 2D array with 2 rows
#np.arange(10)
#Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#How to stack two arrays vertically?
#Stack arrays a and b vertically
#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#How to stack two arrays horizontally?
#Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
d = np.hstack((a,b))
d

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [3]:
#How to generate custom sequences in numpy without hardcoding?
#desired output array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [4]:
#How to get the common items between two python numpy arrays?
a = np.array([1,2,3,8,3,9,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)
#Get the common items between a and b

array([2, 4, 8, 9])

In [5]:
#How to remove from one array those items that exist in another?
#From array a remove all items present in array b
a = np.array([1,2,3,8,3,9,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [8]:
#How to get the positions where elements of two arrays match?
#Get the positions where elements of a and b match
a = np.array([1,2,3,8,3,9,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 7], dtype=int64),)

In [ ]:
#How to extract all numbers between a given range from a numpy array?
# Get all items between 5 and 10 from a.

In [ ]:
#How to make a python function that handles scalars to work on numpy arrays?
#Convert the function maxx that works on two scalars, to work on two arrays.

In [ ]:
#How to swap two columns in a 2d numpy array?
#Swap columns 1 and 2 in the array arr

In [ ]:
#How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr:

In [ ]:
#How to reverse the rows of a 2D array?
#Reverse the rows of a 2D array arr.

In [ ]:
#How to reverse the columns of a 2D array?
#Reverse the columns of a 2D array arr.

In [ ]:
#How to create a 2D array containing random floats between 5 and 10?

In [ ]:
#How to print only 3 decimal places in python numpy array?

In [ ]:
#How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [ ]:
#How to limit the number of items printed in output of numpy array?

In [ ]:
#How to print the full numpy array without truncating

In [ ]:
#How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [ ]:
#How to extract a particular column from 1D array of tuples?

In [ ]:
#How to convert a 1d array of tuples to a 2d numpy array?

In [ ]:
#How to compute the mean, median, standard deviation of a numpy array?

In [ ]:
#How to normalize an array so the values range exactly between 0 and 1?

In [ ]:
#How to compute the softmax score?

In [ ]:
#How to find the percentile scores of a numpy array?

In [ ]:
#How to insert values at random positions in an array?

In [ ]:
#How to find the position of missing values in numpy array?

In [ ]:
#How to filter a numpy array based on two or more conditions?

In [ ]:
#How to drop rows that contain a missing value from a numpy array?

In [ ]:
#How to find the correlation between two columns of a numpy array?

In [ ]:
#How to find if a given array has any null values?

In [ ]:
#How to replace all missing values with 0 in a numpy array?

In [ ]:
#How to find the count of unique values in a numpy array?

In [ ]:
#How to convert a numeric to a categorical (text) array?

In [ ]:
#How to create a new column from existing columns of a numpy array?

In [ ]:
#How to do probabilistic sampling in numpy?

In [ ]:
#How to get the second largest value of an array when grouped by another array?

In [ ]:
#How to sort a 2D array by a column

In [ ]:
#How to find the most frequent value in a numpy array?

In [ ]:
#How to find the position of the first occurrence of a value greater than a given value?

In [ ]:
#How to replace all values greater than a given value to a given cutoff?

In [ ]:
#How to get the positions of top n values from a numpy array?

In [ ]:
#How to compute the row wise counts of all possible values in an array?

In [ ]:
#How to convert an array of arrays into a flat 1d array?

In [ ]:
#How to generate one-hot encodings for an array in numpy?

In [ ]:
#How to create row numbers grouped by a categorical variable?

In [ ]:
#How to create groud ids based on a given categorical variable?

In [ ]:
#How to rank items in an array using numpy?

In [ ]:
#How to rank items in a multidimensional array using numpy?

In [ ]:
#How to find the maximum value in each row of a numpy array 2d?

In [ ]:
#How to compute the min-by-max for each row for a numpy array 2d?

In [ ]:
#How to find the duplicate records in a numpy array?

In [ ]:
#How to find the grouped mean in numpy?

In [ ]:
#How to convert a PIL image to numpy array?

In [ ]:
#How to drop all missing values from a numpy array?

In [ ]:
#How to compute the euclidean distance between two arrays?

In [ ]:
#How to find all the local maxima (or peaks) in a 1d array?

In [ ]:
#How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?

In [ ]:
#How to find the index of n'th repetition of an item in an array

In [ ]:
#How to convert numpy's datetime64 object to datetime's datetime object?

In [ ]:
#How to compute the moving average of a numpy array?

In [ ]:
#How to create a numpy array sequence given only the starting point, length and the step?

In [ ]:
#How to fill in missing dates in an irregular series of numpy dates?

In [ ]:
#How to create strides from a given 1D array?